version: '3'
services:
  postgres:
    image: postgres:15
    container_name: mlocks_task_manager_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mlocks_task_manager
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mlocks_bridge

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mlocks_task_manager_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
      - ./config/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./config/definitions.json:/etc/rabbitmq/definitions.json
      - ./config/init-rabbitmq.sh:/usr/local/bin/init-rabbitmq.sh
    command: sh /usr/local/bin/init-rabbitmq.sh
    networks:
      - mlocks_bridge

  user-service:
    build: .
    container_name: mlocks_task_manager_user_service
    environment:
        DATABASE_HOST: postgres
        DATABASE_PORT: 5432
        DATABASE_USER: postgres
        DATABASE_PASSWORD: password
        DATABASE_NAME: mlocks_task_manager
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_PORT: 5672
        RABBITMQ_USER: guest
        RABBITMQ_PASS: guest
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3000:3000"
    volumes:
      - ./src/user-service:/app/src
      - ./package.json:/app/package.json
    command: npm run start:dev
    networks:
      - mlocks_bridge

  task-service:
    build: .
    container_name: mlocks_task_manager_task_service
    environment:
        DATABASE_HOST: postgres
        DATABASE_PORT: 5432
        DATABASE_USER: postgres
        DATABASE_PASSWORD: password
        DATABASE_NAME: mlocks_task_manager
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_PORT: 5672
        RABBITMQ_USER: guest
        RABBITMQ_PASS: guest
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3001:3000"
    volumes:
      - ./src/task-service:/app/src
      - ./package.json:/app/package.json
    command: npm run start:dev
    networks:
      - mlocks_bridge

  notification-service:
    build: .
    container_name: mlocks_task_manager_notification_service
    environment:
        DATABASE_HOST: postgres
        DATABASE_PORT: 5432
        DATABASE_USER: postgres
        DATABASE_PASSWORD: password
        DATABASE_NAME: mlocks_task_manager
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_PORT: 5672
        RABBITMQ_USER: guest
        RABBITMQ_PASS: guest
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3002:3000"
    volumes:
      - ./src/notification-service:/app/src
      - ./package.json:/app/package.json
    command: npm run start:dev
    networks:
      - mlocks_bridge
      
networks:
  mlocks_bridge:
    driver: bridge
    
volumes:
  pgdata:
  rabbitmqdata: