version: '3'
services:
  postgres:
    image: postgres:15
    container_name: mlocks_task_manager_postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mlocks_bridge

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mlocks_task_manager_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - mlocks_bridge

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mlocks_task_manager_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - mlocks_bridge

  user-service:
    build: .
    container_name: mlocks_task_manager_user_service
    environment:
        DATABASE_HOST: ${DATABASE_HOST}
        DATABASE_PORT: ${DATABASE_PORT}
        DATABASE_USER: ${DATABASE_USER}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_NAME: ${DATABASE_NAME}
        RABBITMQ_HOST: ${RABBITMQ_HOST}
        RABBITMQ_PORT: ${RABBITMQ_PORT}
        RABBITMQ_USER: ${RABBITMQ_USER}
        RABBITMQ_PASS: ${RABBITMQ_PASS}
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3000:3000"
    volumes:
      - ./src/user-service:/app/src
      - ./package.json:/app/package.json
    command: npm run start:dev
    networks:
      - mlocks_bridge

  task-service:
    build: .
    container_name: mlocks_task_manager_task_service
    environment:
        DATABASE_HOST: ${DATABASE_HOST}
        DATABASE_PORT: ${DATABASE_PORT}
        DATABASE_USER: ${DATABASE_USER}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_NAME: ${DATABASE_NAME}
        RABBITMQ_HOST: ${RABBITMQ_HOST}
        RABBITMQ_PORT: ${RABBITMQ_PORT}
        RABBITMQ_USER: ${RABBITMQ_USER}
        RABBITMQ_PASS: ${RABBITMQ_PASS}
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3001:3000"
    volumes:
      - ./src/task-service:/app/src
      - ./package.json:/app/package.json
    command: npm run start:dev
    networks:
      - mlocks_bridge

  notification-service:
    build: .
    container_name: mlocks_task_manager_notification_service
    environment:
        DATABASE_HOST: ${DATABASE_HOST}
        DATABASE_PORT: ${DATABASE_PORT}
        DATABASE_USER: ${DATABASE_USER}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_NAME: ${DATABASE_NAME}
        RABBITMQ_HOST: ${RABBITMQ_HOST}
        RABBITMQ_PORT: ${RABBITMQ_PORT}
        RABBITMQ_USER: ${RABBITMQ_USER}
        RABBITMQ_PASS: ${RABBITMQ_PASS}
        MAILHOG_HOST: ${MAILHOG_HOST}
        MAILHOG_PORT: ${MAILHOG_PORT}
    depends_on:
      - postgres
      - rabbitmq
      - mailhog
    ports:
      - "3002:3000"
    volumes:
      - ./src/notification-service:/app/src
      - ./package.json:/app/package.json
    command: npm run start:dev
    networks:
      - mlocks_bridge
      
networks:
  mlocks_bridge:
    driver: bridge
    
volumes:
  pgdata:
  rabbitmqdata: